version: "3.9"
networks:
  guacamole_network:
    driver: bridge
  
services:
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole
    networks:
      guacamole_network:
    restart: always
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_PASSWORD: 'PASSWORD'
      POSTGRES_USER: guacamole_user
    ports:
    - 8080:8080/tcp

  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      guacamole_network:
    restart: always
    volumes:
    - /home/$USER/dockerdata/guacamole/guacd/drive:/drive:rw
    - /home/$USER/dockerdata/guacamole/guacd/record:/record:rw

  postgres:
    container_name: postgres_guacamole
    image: postgres:14.2
    networks:
      guacamole_network:
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'PASSWORD'
      POSTGRES_USER: guacamole_user
    volumes:
    - /home/$USER/dockerdata/guacamole/postgres/init:/docker-entrypoint-initdb.d:ro
    - /home/$USER/dockerdata/guacamole/postgres/data:/var/lib/postgresql/data:rw
